version: '3.8'

services:
  web:
    build: .
    ports:
      - "8090:80"
    volumes:
      - ./database:/usr/local/apache2/data
      - ./templates:/usr/local/apache2/htdocs/templates
      - ./static:/usr/local/apache2/htdocs/static
      - ./cgi-bin:/usr/local/apache2/cgi-bin
    environment:
      - PERL5LIB=/usr/local/apache2/cgi-bin